import { chromium } from 'playwright';
const SP = process.env.SP ?? 'e2e-output';
import { mkdirSync } from 'node:fs';
mkdirSync(SP, { recursive: true });
const browser = await chromium.launch(process.env.CHROMIUM_PATH ? { executablePath: process.env.CHROMIUM_PATH } : {});
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
const errors = [];
page.on('pageerror', (e) => errors.push('pageerror: ' + e.message));
page.on('console', (m) => { if (m.type() === 'error') errors.push('console: ' + m.text()); });
await page.goto('http://localhost:5173');
await page.screenshot({ path: `${SP}/01-menu.png` });
await page.click('text=New Dynasty');
await page.waitForSelector('.school-card');
await page.screenshot({ path: `${SP}/02-select.png` });
await page.click('.tab:has-text("SEC")');
await page.click('.school-card:has-text("Alabama")');
await page.waitForSelector('text=Become Head Coach');
await page.screenshot({ path: `${SP}/03-overview.png`, fullPage: true });
await page.fill('input[placeholder="Coach"]', 'Sam');
await page.fill('input[placeholder="Taylor"]', 'Rivers');
await page.click('text=Become Head Coach');
await page.waitForSelector('.hub-nav', { timeout: 20000 });
await page.screenshot({ path: `${SP}/04-hub.png`, fullPage: true });
for (const tab of ['Team', 'Depth Chart', 'Schedule', 'Game Plan', 'Top 25', 'Conference', 'News', 'Coach Profile']) {
  await page.click(`.hub-nav button:has-text("${tab}")`);
  await page.waitForTimeout(250);
  await page.screenshot({ path: `${SP}/05-${tab.replace(/ /g, '')}.png`, fullPage: false });
}
await page.click('.hub-nav button:has-text("Home")');
await page.click('text=Play Week');
await page.waitForSelector('canvas');
await page.waitForTimeout(6000);
await page.screenshot({ path: `${SP}/06-game-kick.png` });
await page.waitForTimeout(9000);
await page.screenshot({ path: `${SP}/07-game-play.png` });
await page.waitForTimeout(5000);
await page.screenshot({ path: `${SP}/08-game-play2.png` });
await page.click('text=All-22 Cam');
await page.waitForTimeout(4000);
await page.screenshot({ path: `${SP}/09-overhead.png` });
await page.click('text=Broadcast Cam');
await page.click('text=To Halftime');
await page.waitForTimeout(1500);
await page.screenshot({ path: `${SP}/10-half.png` });
await page.click('text=Sim To End');
await page.waitForSelector('.final-overlay', { timeout: 15000 });
await page.screenshot({ path: `${SP}/11-final.png` });
await page.click('text=Return to Dynasty');
await page.waitForSelector('.hub-nav');
await page.waitForTimeout(500);
await page.screenshot({ path: `${SP}/12-hub-after.png`, fullPage: true });
console.log('ERRORS', errors.length, errors.slice(0, 10).join('\n'));
await browser.close();
