// Writes docs/ASSET_AUDIT.md: every supplied source file, where it was copied, what uses it, and hash verification.
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { GEAR_ASSETS, LOGO_ASSETS } from '../src/assets/registry';
import { getTeam } from '../src/data/teams';
import manifest from '../src/data/logo-manifest.json';

const sha = (p: string) => (existsSync(p) ? createHash('sha256').update(readFileSync(p)).digest('hex') : 'MISSING');
const sums = Object.fromEntries(readFileSync('docs/correction-pack/SHA256SUMS.txt', 'utf8').trim().split('\n').map((l) => { const [h, f] = l.split(/\s+/); return [f.replace(/^\.\//, ''), h]; }));
const ok = (a: string, b: string) => (a === b ? '✅ match' : `❌ ${a.slice(0, 12)}`);
let md = `# Asset audit\n\nGenerated by \`npx tsx scripts/assetAudit.ts\`. "Pack SHA-256" comes from the correction pack's SHA256SUMS.txt; "Copied" re-hashes the file inside \`public/\`.\n\n## Gear (shop artwork, unchanged originals)\n\n| Item ID | Name | Slot | Supplied file | Imported path | Pack SHA-256 | Copied |\n| --- | --- | --- | --- | --- | --- | --- |\n`;
for (const g of GEAR_ASSETS) md += `| \`${g.itemId}\` | ${g.name} | ${g.slot} | \`${g.source}\` | \`public/${g.path}\` | \`${sums[g.source]}\` | ${ok(sha('public/' + g.path), sums[g.source])} |\n`;
md += `\n## School logos\n\n| Team ID | School | Mascot | Supplied file | Imported path | Official source | Pack SHA-256 | Copied |\n| --- | --- | --- | --- | --- | --- | --- | --- |\n`;
for (const l of LOGO_ASSETS) {
  const m = manifest.find((x) => x.id === l.teamId)!;
  const t = getTeam(l.teamId);
  md += `| \`${l.teamId}\` | ${t.shortName} | ${t.mascot} | \`${l.source}\` | \`public/${l.path}\` | ${m.schoolPage} | \`${sums[l.source]}\` | ${ok(sha('public/' + l.path), sums[l.source])} |\n`;
}
md += `\n## Reference material\n\n| Supplied file | Imported path | Copied |\n| --- | --- | --- |\n`;
for (const [src, dst] of [['Character_Motion_Guide.png', 'public/assets/reference/Character_Motion_Guide.png'], ['IMG_3755.png', 'public/assets/reference/IMG_3755.png'], ['LCPS_Bowl_Character_Techpack.md', 'docs/correction-pack/LCPS_Bowl_Character_Techpack.md'], ['logo-manifest.json', 'src/data/logo-manifest.json']]) md += `| \`${src}\` | \`${dst}\` | ${ok(sha(dst), sums[src])} |\n`;
md += `\nLogos are school-site logos/lockups downloaded from each school's official LCPS page (see logo-manifest.json). They are not verified football helmet decals. The tiny in-game helmet mark is a downsampled derivative of the full logo. This is a personal, non-commercial project and is not endorsed by LCPS, the schools or any equipment brand.\n`;
writeFileSync('docs/ASSET_AUDIT.md', md);
console.log(md.includes('❌') ? 'AUDIT FAILED' : 'audit ok');
