import { chromium } from 'playwright';
import { readFileSync } from 'node:fs';
const OUT = process.argv[2];
const URL = process.argv[3] ?? 'http://127.0.0.1:5199/';
const save = JSON.parse(readFileSync(process.argv[4], 'utf8'));
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH ?? '/opt/pw-browsers/chromium' });
const page = await browser.newPage({ viewport: { width: 1360, height: 900 } });
const errors = [];
page.on('pageerror', (e) => errors.push(String(e)));
const shot = (n) => page.screenshot({ path: `${OUT}/${n}.png` });
const wait = (ms) => page.waitForTimeout(ms);
await page.goto(URL);
await wait(800);
await page.evaluate(async ({ raw, meta }) => {
  await new Promise((res) => {
    const req = indexedDB.open('lcps-bowl', 1);
    req.onupgradeneeded = () => req.result.createObjectStore('dynasties');
    req.onsuccess = () => { const tx = req.result.transaction('dynasties', 'readwrite'); tx.objectStore('dynasties').put(raw, 'lcps-bowl:dynasty:1'); tx.oncomplete = res; };
  });
  localStorage.setItem('lcps-bowl:meta:1', JSON.stringify(meta));
  localStorage.setItem('lcps-bowl:last-slot', '1');
}, save);
await page.reload();
await wait(1000);
await page.click('text=CONTINUE DYNASTY');
await wait(1200);
await shot('s01-season-end');
await page.click('.dyn-tab:has-text("PLAYOFF PICTURE")');
await wait(300);
await shot('s02-bracket');
await page.click('.dyn-tab:has-text("RECORDS")');
await wait(300);
await shot('s03-records');
await page.click('.dyn-tab:has-text("HOME")');
await wait(300);
await page.click('text=BEGIN OFFSEASON');
await wait(1500);
await shot('s04-offseason');
await page.click('text=/START \\d+ SEASON/');
await wait(600);
await shot('s05-new-season');
// Play a game via PLAY GAME → pause → sim to end
await page.click('text=PLAY GAME');
await wait(1500);
await shot('s06-intro');
await page.keyboard.press('Enter');
await wait(2500);
await page.keyboard.press('Escape');
await wait(300);
await page.click('text=SIM TO END');
await wait(1500);
await shot('s07-final');
await page.click('text=CONTINUE ▸');
await page.waitForSelector('text=AROUND LOUDOUN COUNTY', { timeout: 120000 });
await wait(500);
await shot('s08-week');
console.log(JSON.stringify({ errors }));
await browser.close();
