/**
 * Fictional name pools. Players are generated by randomly combining first and last names,
 * so they are not real people (and never real minors).
 */
export const FIRST_NAMES = [
  'Aiden', 'Andre', 'Austin', 'Blake', 'Brady', 'Braylon', 'Brennan', 'Brody', 'Caleb', 'Cam', 'Carson', 'Carter',
  'Chase', 'Cole', 'Colton', 'Connor', 'Cooper', 'Corey', 'Dalton', 'Damon', 'Dante', 'Darius', 'Davis', 'Dawson',
  'Declan', 'Derek', 'Devin', 'Dominic', 'Drew', 'Dylan', 'Eli', 'Elijah', 'Emmett', 'Ethan', 'Evan', 'Gabe', 'Gavin',
  'Grady', 'Grant', 'Griffin', 'Hayden', 'Hunter', 'Isaac', 'Isaiah', 'Jace', 'Jackson', 'Jalen', 'Jamal', 'Jared',
  'Javier', 'Jaylen', 'Jordan', 'Josiah', 'Julian', 'Kai', 'Kaden', 'Keegan', 'Kendall', 'Kevin', 'Kyle', 'Landon',
  'Lane', 'Logan', 'Lucas', 'Luke', 'Malik', 'Marcus', 'Mason', 'Mateo', 'Micah', 'Miles', 'Nate', 'Nico', 'Noah',
  'Omar', 'Owen', 'Parker', 'Preston', 'Quinn', 'Reed', 'Reggie', 'Riley', 'Ryan', 'Sam', 'Santiago', 'Sean',
  'Seth', 'Shane', 'Spencer', 'Tanner', 'Tate', 'Terrell', 'Theo', 'Trent', 'Trevor', 'Tristan', 'Ty', 'Tyler',
  'Victor', 'Wade', 'Wes', 'Xavier', 'Zach', 'Zion', 'Amir', 'Arjun', 'Ben', 'Bryce', 'Chris', 'Diego', 'Ezra',
  'Finn', 'Hank', 'Ian', 'Jake', 'Joel', 'Kobe', 'Leo', 'Mike', 'Nolan', 'Pierce', 'Rashad', 'Rory', 'Sully', 'Troy',
];

export const LAST_NAMES = [
  'Adams', 'Alvarez', 'Bailey', 'Baker', 'Banks', 'Barnes', 'Bell', 'Bennett', 'Brooks', 'Bryant', 'Burke',
  'Butler', 'Caldwell', 'Campbell', 'Carter', 'Castillo', 'Chambers', 'Chen', 'Clark', 'Coleman', 'Collins',
  'Cooper', 'Cruz', 'Daniels', 'Davis', 'Dawson', 'Diaz', 'Dixon', 'Doyle', 'Edwards', 'Ellis', 'Evans', 'Fisher',
  'Fleming', 'Ford', 'Foster', 'Fox', 'Garcia', 'Gibson', 'Graham', 'Grant', 'Gray', 'Green', 'Griffin', 'Hall',
  'Hamilton', 'Harper', 'Harris', 'Hayes', 'Henderson', 'Hill', 'Holmes', 'Howard', 'Hughes', 'Hunt', 'Jackson',
  'James', 'Jenkins', 'Johnson', 'Jordan', 'Kelly', 'Kennedy', 'Kim', 'King', 'Knight', 'Lane', 'Lawson', 'Lee',
  'Lewis', 'Long', 'Lopez', 'Marsh', 'Martin', 'Mason', 'McCoy', 'Meyer', 'Miller', 'Mitchell', 'Moore', 'Morgan',
  'Morris', 'Murphy', 'Nash', 'Nelson', 'Nguyen', 'Owens', 'Palmer', 'Parker', 'Patel', 'Perry', 'Peterson',
  'Pierce', 'Porter', 'Powell', 'Price', 'Ramirez', 'Reed', 'Reyes', 'Rivera', 'Roberts', 'Robinson', 'Rogers',
  'Ross', 'Russell', 'Sanders', 'Shaw', 'Simmons', 'Smith', 'Spencer', 'Stewart', 'Stone', 'Sullivan', 'Taylor',
  'Thomas', 'Thompson', 'Torres', 'Tucker', 'Turner', 'Vaughn', 'Walker', 'Wallace', 'Ward', 'Warren', 'Watson',
  'Webb', 'Wells', 'West', 'White', 'Williams', 'Wilson', 'Wood', 'Wright', 'Young', 'Okafor', 'Haddad', 'Singh',
  'Kowalski', 'Novak', "O'Brien", 'Ferreira', 'Mensah', 'Park', 'Romero', 'Santos', 'Vega', 'Whitaker', 'Yates',
];
